# Generated by Django 5.2.7 on 2025-10-15 13:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °F', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)])),
                ('heart_rate', models.IntegerField(blank=True, help_text='Beats per minute', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)])),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute', null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(40)])),
                ('oxygen_saturation', models.IntegerField(blank=True, help_text='SpO2 percentage', null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('chief_complaint', models.TextField(help_text='Main reason for visit')),
                ('present_illness', models.TextField(blank=True, help_text='History of present illness')),
                ('physical_examination', models.TextField(blank=True)),
                ('diagnosis', models.TextField(help_text='Medical diagnosis')),
                ('treatment_plan', models.TextField(help_text='Recommended treatment')),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies')),
                ('current_medications', models.TextField(blank=True)),
                ('past_medical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('social_history', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='users.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('insurance', 'Insurance Document'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='medical_documents/')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='users.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Test'), ('imaging', 'Imaging'), ('biopsy', 'Biopsy'), ('other', 'Other')], default='blood', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Pre-test instructions')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('result', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('requires_attention', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_tests', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='users.patient')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice daily', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 7 days', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='users.doctor')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('vaccine_type', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('dose_number', models.IntegerField(default=1, help_text='Which dose (1st, 2nd, booster)')),
                ('administration_date', models.DateField()),
                ('administration_site', models.CharField(blank=True, help_text='e.g., Left arm, Right arm', max_length=100)),
                ('next_dose_date', models.DateField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccines', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='users.patient')),
            ],
            options={
                'ordering': ['-administration_date'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', '-created_at'], name='medical_rec_patient_2431c8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['doctor', '-created_at'], name='medical_rec_doctor__ea7f05_idx'),
        ),
    ]
